name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-k8s:
    name: Deploy to Kubernetes
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    env:
      NAMESPACE: wisecow
      KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
    steps:
      - name: Validate KUBECONFIG
        run: |
          if [ -z "${KUBECONFIG_DATA}" ]; then
            echo "Error: KUBECONFIG secret is not set. Add it under Settings → Secrets → Actions → KUBECONFIG."
            exit 1
          fi

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubectl
        run: |
          echo "${KUBECONFIG_DATA}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl version --client

      - name: Verify Kubernetes Access
        run: |
          kubectl config get-contexts
          kubectl get nodes || echo "Warning: Unable to list nodes. Check cluster access."

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/namespace.yaml || echo "Namespace may already exist."
          kubectl apply -f k8s/service.yaml -n $NAMESPACE

          IMAGE_TAG="ghcr.io/${{ github.repository }}:${{ github.sha }}"
          sed "s|<IMAGE_PLACEHOLDER>|$IMAGE_TAG|g" k8s/deployment.yaml > deployment-temp.yaml

          kubectl apply -f deployment-temp.yaml -n $NAMESPACE
          kubectl rollout status deployment/wisecow-deployment -n $NAMESPACE
          rm deployment-temp.yaml
